// Generated by gencpp from file pid/wheel_vel.msg
// DO NOT EDIT!


#ifndef PID_MESSAGE_WHEEL_VEL_H
#define PID_MESSAGE_WHEEL_VEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>

namespace pid
{
template <class ContainerAllocator>
struct wheel_vel_
{
  typedef wheel_vel_<ContainerAllocator> Type;

  wheel_vel_()
    : left_vel()
    , right_vel()  {
    }
  wheel_vel_(const ContainerAllocator& _alloc)
    : left_vel(_alloc)
    , right_vel(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64_<ContainerAllocator>  _left_vel_type;
  _left_vel_type left_vel;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _right_vel_type;
  _right_vel_type right_vel;





  typedef boost::shared_ptr< ::pid::wheel_vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pid::wheel_vel_<ContainerAllocator> const> ConstPtr;

}; // struct wheel_vel_

typedef ::pid::wheel_vel_<std::allocator<void> > wheel_vel;

typedef boost::shared_ptr< ::pid::wheel_vel > wheel_velPtr;
typedef boost::shared_ptr< ::pid::wheel_vel const> wheel_velConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pid::wheel_vel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pid::wheel_vel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pid::wheel_vel_<ContainerAllocator1> & lhs, const ::pid::wheel_vel_<ContainerAllocator2> & rhs)
{
  return lhs.left_vel == rhs.left_vel &&
    lhs.right_vel == rhs.right_vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pid::wheel_vel_<ContainerAllocator1> & lhs, const ::pid::wheel_vel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pid

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pid::wheel_vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pid::wheel_vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pid::wheel_vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pid::wheel_vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pid::wheel_vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pid::wheel_vel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pid::wheel_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3893aed4c3e7acb03e6a5f6c31725f32";
  }

  static const char* value(const ::pid::wheel_vel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3893aed4c3e7acb0ULL;
  static const uint64_t static_value2 = 0x3e6a5f6c31725f32ULL;
};

template<class ContainerAllocator>
struct DataType< ::pid::wheel_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pid/wheel_vel";
  }

  static const char* value(const ::pid::wheel_vel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pid::wheel_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float64 left_vel\n"
"std_msgs/Float64 right_vel\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::pid::wheel_vel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pid::wheel_vel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_vel);
      stream.next(m.right_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wheel_vel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pid::wheel_vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pid::wheel_vel_<ContainerAllocator>& v)
  {
    s << indent << "left_vel: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.left_vel);
    s << indent << "right_vel: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.right_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PID_MESSAGE_WHEEL_VEL_H
