//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the mpc_node package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __mpc_node__MPC_DYNAMICCONFIG_H__
#define __mpc_node__MPC_DYNAMICCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace mpc_node
{
  class mpc_dynamicConfigStatics;

  class mpc_dynamicConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(mpc_dynamicConfig &config, const mpc_dynamicConfig &max, const mpc_dynamicConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const mpc_dynamicConfig &config1, const mpc_dynamicConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, mpc_dynamicConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const mpc_dynamicConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, mpc_dynamicConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const mpc_dynamicConfig &config) const = 0;
      virtual void getValue(const mpc_dynamicConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T mpc_dynamicConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T mpc_dynamicConfig::* field;

      virtual void clamp(mpc_dynamicConfig &config, const mpc_dynamicConfig &max, const mpc_dynamicConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const mpc_dynamicConfig &config1, const mpc_dynamicConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, mpc_dynamicConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const mpc_dynamicConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, mpc_dynamicConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const mpc_dynamicConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const mpc_dynamicConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, mpc_dynamicConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, mpc_dynamicConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<mpc_dynamicConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(mpc_dynamicConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("max_speed"==(*_i)->name){max_speed = boost::any_cast<double>(val);}
        if("path_length"==(*_i)->name){path_length = boost::any_cast<double>(val);}
        if("goal_radius"==(*_i)->name){goal_radius = boost::any_cast<double>(val);}
        if("controller_freq"==(*_i)->name){controller_freq = boost::any_cast<double>(val);}
        if("mpc_steps"==(*_i)->name){mpc_steps = boost::any_cast<double>(val);}
        if("mpc_ref_cte"==(*_i)->name){mpc_ref_cte = boost::any_cast<double>(val);}
        if("mpc_ref_epsi"==(*_i)->name){mpc_ref_epsi = boost::any_cast<double>(val);}
        if("mpc_ref_vel"==(*_i)->name){mpc_ref_vel = boost::any_cast<double>(val);}
        if("mpc_w_cte"==(*_i)->name){mpc_w_cte = boost::any_cast<double>(val);}
        if("mpc_w_epsi"==(*_i)->name){mpc_w_epsi = boost::any_cast<double>(val);}
        if("mpc_w_vel"==(*_i)->name){mpc_w_vel = boost::any_cast<double>(val);}
        if("mpc_w_delta"==(*_i)->name){mpc_w_delta = boost::any_cast<double>(val);}
        if("mpc_w_accel"==(*_i)->name){mpc_w_accel = boost::any_cast<double>(val);}
        if("mpc_w_delta_d"==(*_i)->name){mpc_w_delta_d = boost::any_cast<double>(val);}
        if("mpc_w_accel_d"==(*_i)->name){mpc_w_accel_d = boost::any_cast<double>(val);}
        if("mpc_max_steering"==(*_i)->name){mpc_max_steering = boost::any_cast<double>(val);}
        if("mpc_max_throttle"==(*_i)->name){mpc_max_throttle = boost::any_cast<double>(val);}
        if("mpc_max_gama"==(*_i)->name){mpc_max_gama = boost::any_cast<double>(val);}
      }
    }

    double max_speed;
double path_length;
double goal_radius;
double controller_freq;
double mpc_steps;
double mpc_ref_cte;
double mpc_ref_epsi;
double mpc_ref_vel;
double mpc_w_cte;
double mpc_w_epsi;
double mpc_w_vel;
double mpc_w_delta;
double mpc_w_accel;
double mpc_w_delta_d;
double mpc_w_accel_d;
double mpc_max_steering;
double mpc_max_throttle;
double mpc_max_gama;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_speed;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double path_length;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double goal_radius;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double controller_freq;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mpc_steps;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mpc_ref_cte;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mpc_ref_epsi;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mpc_ref_vel;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mpc_w_cte;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mpc_w_epsi;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mpc_w_vel;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mpc_w_delta;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mpc_w_accel;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mpc_w_delta_d;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mpc_w_accel_d;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mpc_max_steering;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mpc_max_throttle;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double mpc_max_gama;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("mpc_dynamicConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const mpc_dynamicConfig &__max__ = __getMax__();
      const mpc_dynamicConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const mpc_dynamicConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const mpc_dynamicConfig &__getDefault__();
    static const mpc_dynamicConfig &__getMax__();
    static const mpc_dynamicConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const mpc_dynamicConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void mpc_dynamicConfig::ParamDescription<std::string>::clamp(mpc_dynamicConfig &config, const mpc_dynamicConfig &max, const mpc_dynamicConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class mpc_dynamicConfigStatics
  {
    friend class mpc_dynamicConfig;

    mpc_dynamicConfigStatics()
    {
mpc_dynamicConfig::GroupDescription<mpc_dynamicConfig::DEFAULT, mpc_dynamicConfig> Default("Default", "", 0, 0, true, &mpc_dynamicConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_speed = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_speed = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_speed = 1.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("max_speed", "double", 0, "max_speed", "", &mpc_dynamicConfig::max_speed)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("max_speed", "double", 0, "max_speed", "", &mpc_dynamicConfig::max_speed)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.path_length = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.path_length = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.path_length = 6.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("path_length", "double", 0, "path_length", "", &mpc_dynamicConfig::path_length)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("path_length", "double", 0, "path_length", "", &mpc_dynamicConfig::path_length)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.goal_radius = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.goal_radius = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.goal_radius = 0.2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("goal_radius", "double", 0, "goal_radius", "", &mpc_dynamicConfig::goal_radius)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("goal_radius", "double", 0, "goal_radius", "", &mpc_dynamicConfig::goal_radius)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.controller_freq = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.controller_freq = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.controller_freq = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("controller_freq", "double", 0, "controller_freq", "", &mpc_dynamicConfig::controller_freq)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("controller_freq", "double", 0, "controller_freq", "", &mpc_dynamicConfig::controller_freq)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mpc_steps = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mpc_steps = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mpc_steps = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_steps", "double", 0, "mpc_steps", "", &mpc_dynamicConfig::mpc_steps)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_steps", "double", 0, "mpc_steps", "", &mpc_dynamicConfig::mpc_steps)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mpc_ref_cte = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mpc_ref_cte = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mpc_ref_cte = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_ref_cte", "double", 0, "mpc_ref_cte", "", &mpc_dynamicConfig::mpc_ref_cte)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_ref_cte", "double", 0, "mpc_ref_cte", "", &mpc_dynamicConfig::mpc_ref_cte)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mpc_ref_epsi = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mpc_ref_epsi = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mpc_ref_epsi = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_ref_epsi", "double", 0, "mpc_ref_epsi", "", &mpc_dynamicConfig::mpc_ref_epsi)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_ref_epsi", "double", 0, "mpc_ref_epsi", "", &mpc_dynamicConfig::mpc_ref_epsi)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mpc_ref_vel = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mpc_ref_vel = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mpc_ref_vel = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_ref_vel", "double", 0, "mpc_ref_vel", "", &mpc_dynamicConfig::mpc_ref_vel)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_ref_vel", "double", 0, "mpc_ref_vel", "", &mpc_dynamicConfig::mpc_ref_vel)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mpc_w_cte = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mpc_w_cte = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mpc_w_cte = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_w_cte", "double", 0, "mpc_w_cte", "", &mpc_dynamicConfig::mpc_w_cte)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_w_cte", "double", 0, "mpc_w_cte", "", &mpc_dynamicConfig::mpc_w_cte)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mpc_w_epsi = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mpc_w_epsi = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mpc_w_epsi = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_w_epsi", "double", 0, "mpc_w_epsi", "", &mpc_dynamicConfig::mpc_w_epsi)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_w_epsi", "double", 0, "mpc_w_epsi", "", &mpc_dynamicConfig::mpc_w_epsi)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mpc_w_vel = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mpc_w_vel = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mpc_w_vel = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_w_vel", "double", 0, "mpc_w_vel", "", &mpc_dynamicConfig::mpc_w_vel)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_w_vel", "double", 0, "mpc_w_vel", "", &mpc_dynamicConfig::mpc_w_vel)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mpc_w_delta = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mpc_w_delta = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mpc_w_delta = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_w_delta", "double", 0, "mpc_w_delta", "", &mpc_dynamicConfig::mpc_w_delta)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_w_delta", "double", 0, "mpc_w_delta", "", &mpc_dynamicConfig::mpc_w_delta)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mpc_w_accel = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mpc_w_accel = 1000.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mpc_w_accel = 2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_w_accel", "double", 0, "mpc_w_accel", "", &mpc_dynamicConfig::mpc_w_accel)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_w_accel", "double", 0, "mpc_w_accel", "", &mpc_dynamicConfig::mpc_w_accel)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mpc_w_delta_d = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mpc_w_delta_d = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mpc_w_delta_d = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_w_delta_d", "double", 0, "mpc_w_delta_d", "", &mpc_dynamicConfig::mpc_w_delta_d)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_w_delta_d", "double", 0, "mpc_w_delta_d", "", &mpc_dynamicConfig::mpc_w_delta_d)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mpc_w_accel_d = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mpc_w_accel_d = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mpc_w_accel_d = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_w_accel_d", "double", 0, "mpc_w_accel_d", "", &mpc_dynamicConfig::mpc_w_accel_d)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_w_accel_d", "double", 0, "mpc_w_accel_d", "", &mpc_dynamicConfig::mpc_w_accel_d)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mpc_max_steering = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mpc_max_steering = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mpc_max_steering = 0.436;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_max_steering", "double", 0, "mpc_max_steering", "", &mpc_dynamicConfig::mpc_max_steering)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_max_steering", "double", 0, "mpc_max_steering", "", &mpc_dynamicConfig::mpc_max_steering)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mpc_max_throttle = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mpc_max_throttle = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mpc_max_throttle = 0.8;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_max_throttle", "double", 0, "mpc_max_throttle", "", &mpc_dynamicConfig::mpc_max_throttle)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_max_throttle", "double", 0, "mpc_max_throttle", "", &mpc_dynamicConfig::mpc_max_throttle)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.mpc_max_gama = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.mpc_max_gama = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.mpc_max_gama = 0.7;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_max_gama", "double", 0, "mpc_max_gama", "", &mpc_dynamicConfig::mpc_max_gama)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(mpc_dynamicConfig::AbstractParamDescriptionConstPtr(new mpc_dynamicConfig::ParamDescription<double>("mpc_max_gama", "double", 0, "mpc_max_gama", "", &mpc_dynamicConfig::mpc_max_gama)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(mpc_dynamicConfig::AbstractGroupDescriptionConstPtr(new mpc_dynamicConfig::GroupDescription<mpc_dynamicConfig::DEFAULT, mpc_dynamicConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<mpc_dynamicConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<mpc_dynamicConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<mpc_dynamicConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    mpc_dynamicConfig __max__;
    mpc_dynamicConfig __min__;
    mpc_dynamicConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const mpc_dynamicConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static mpc_dynamicConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &mpc_dynamicConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const mpc_dynamicConfig &mpc_dynamicConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const mpc_dynamicConfig &mpc_dynamicConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const mpc_dynamicConfig &mpc_dynamicConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<mpc_dynamicConfig::AbstractParamDescriptionConstPtr> &mpc_dynamicConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<mpc_dynamicConfig::AbstractGroupDescriptionConstPtr> &mpc_dynamicConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const mpc_dynamicConfigStatics *mpc_dynamicConfig::__get_statics__()
  {
    const static mpc_dynamicConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = mpc_dynamicConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __MPC_DYNAMICRECONFIGURATOR_H__
